version: '3'

services:
  am-role-assignment-batch-service:
    build:
      context: .
    image: hmcts/am-role-assignment-batch-service
    container_name: am-role-assignment-batch-service
    ports:
      - ${SERVER_PORT:-4098}:${SERVER_PORT:-4098}
    environment:
      - ROLE_ASSIGNMENT_DB_USERNAME=am
      - ROLE_ASSIGNMENT_DB_PASSWORD=am
      - POSTGRES_HOST_AUTH_METHOD=trust
      - ROLE_ASSIGNMENT_DB_HOST=am-role-assignment-database
      - ROLE_ASSIGNMENT_DB_NAME=role_assignment
      - ROLE_ASSIGNMENT_DB_PORT=5432
      - ROLE_ASSIGNMENT_DB_OPTIONS
      - JUDICIAL_BOOKING_SERVICE_POSTGRES_USER=am
      - JUDICIAL_BOOKING_SERVICE_POSTGRES_PASS=am
      - JUDICIAL_BOOKING_SERVICE_POSTGRES_HOST=am-judicial-booking-database
      - JUDICIAL_BOOKING_SERVICE_POSTGRES_DATABASE=judicial_booking
      - JUDICIAL_BOOKING_SERVICE_POSTGRES_PORT=5432
      - JUDICIAL_BOOKING_SERVICE_DB_OPTIONS