server:
  port: ${PORT:4099}

management:
  health:
    db:
      enabled: true
    defaults:
      enabled: true
    diskspace:
      enabled: true
  endpoint:
    health:
      enabled: true
      cache:
        time-to-live: 5s
      show-details: "always"
  security:
    enabled: false
  endpoints:
    health:
      sensitive: false
    web:
      base-path: /
      exposure:
        include: 'health'

#If you use a database then uncomment below lines and update db properties accordingly

spring:
  application:
    name: Role Assignment Refresh Batch
  batch:
    initialize-schema: always
    job:
      enabled: true
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    log_statement: all
    properties:
      hibernate:
        ddl-auto: update
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${ROLE_ASSIGNMENT_DB_HOST:localhost}:${ROLE_ASSIGNMENT_DB_PORT:5451}/${ROLE_ASSIGNMENT_DB_NAME:role_assignment}${ROLE_ASSIGNMENT_DB_OPTIONS:?stringtype=unspecified}
    username: ${ROLE_ASSIGNMENT_DB_USERNAME:am}
    password: ${ROLE_ASSIGNMENT_DB_PASSWORD:am}
    properties:
      charSet: UTF-8

delete-expired-records: deleteExpiredRecords
batchjob-name: deleteExpiredRecords
batch-size: 4

csv-file-name: book2.csv
csv-file-path: src/main/resources/
migration:
  masterFlag: ${CCD_AM_MIGRATION_MASTER_FLAG:true}
  renameTables: ${CCD_AM_MIGRATION_RENAME_TABLES_FLAG:false}

azure:
  container-name: amccdras
  account-name: ${AZURE_BLOB_STORAGE_ACCOUNT:amdatamigrationstorage}
  account-key: ${AZURE_BLOB_STORAGE_ACCOUNT_KEY:}

launchdarkly:
  sdk:
    key: ${LD_SDK_KEY:}
    environment: ${LAUNCH_DARKLY_ENV:pr}
    user: am-${LAUNCH_DARKLY_ENV:local}

logging.level.org.springframework.batch.core.step.item.ChunkMonitor: ${APPLICATION_LOGGING_LEVEL:ERROR}

ccd:
  roleNames: '[PETSOLICITOR],[RESPSOLICITOR],[BARRISTER],[CAFCASSSOLICITOR],[EPSMANAGING],[LABARRISTER],[LAMANAGING],
              [LASOLICITOR],[SOLICITOR],[SOLICITOR A],[SOLICITOR B],[SOLICITOR C],[SOLICITOR D],[SOLICITOR E],
              [SOLICITOR F],[SOLICITOR G],[SOLICITOR H],[SOLICITOR I],[SOLICITOR J],[LEGALREPRESENTATIVE]'
