
spring:
  application:
    name: Role Assignment Batch Service
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true
  main:
    web-application-type: none
    allow-bean-definition-overriding: true
    allow-circular-references: true
  jackson:
    default-property-inclusion: NON_NULL
  config:
    import: "optional:configtree:/mnt/secrets/am/"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    log_statement: all
    properties:
      hibernate:
        ddl-auto: update
        jdbc:
          lob:
            non_contextual_creation: true
  flyway.enabled: ${ENABLE_DB_MIGRATE:false}
  flyway.locations: classpath:db/migration
  datasource:
    driverClassName: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://${ROLE_ASSIGNMENT_DB_HOST:localhost}:${ROLE_ASSIGNMENT_DB_PORT:5451}/${ROLE_ASSIGNMENT_DB_NAME:role_assignment}${ROLE_ASSIGNMENT_DB_OPTIONS:?stringtype=unspecified}
    username: ${ROLE_ASSIGNMENT_DB_USERNAME:am}
    password: ${ROLE_ASSIGNMENT_DB_PASSWORD:am}
    properties:
      charSet: UTF-8
  judicial:
    datasource:
      driverClassName: org.postgresql.Driver
      jdbcUrl: jdbc:postgresql://${JUDICIAL_BOOKING_SERVICE_POSTGRES_HOST:localhost}:${JUDICIAL_BOOKING_SERVICE_POSTGRES_PORT:5451}/${JUDICIAL_BOOKING_SERVICE_POSTGRES_DATABASE:judicial_booking}${JUDICIAL_BOOKING_SERVICE_DB_OPTIONS:}
      username: ${JUDICIAL_BOOKING_SERVICE_POSTGRES_USER:am}
      password: ${JUDICIAL_BOOKING_SERVICE_POSTGRES_PASS:am}
      properties:
        charSet: UTF-8
    days: ${DAYS:0}

  ## Sendgrid configuration ##
  mail:
    to: ${EMAIL_LIST:nitish.singla@hmcts.net}
    host: ${EMAIL_HOST:mta.reform.hmcts.net}
    port: 25
    enabled: ${EMAIL_ENABLED:false} # Disabled this property for integration test.
    properties:
      mail-smtp:
        starttls:
          enable: false
        ssl:
          trust: "*"


delete-expired-records: deleteExpiredRecords
delete-expired-judicial-records: deleteExpiredJudicialRecords
batchjob-name: deleteExpiredRecords
batch-size: 4

batch-environment: ${BATCH_ENV:local}

logging.level.org.springframework.batch.core.step.item.ChunkMonitor: ${APPLICATION_LOGGING_LEVEL:ERROR}

sendgrid:
  key: ${AM_SENDGRID_API_KEY:dummyValue}
  mail:
    from: ${AM_SENDGRID_API_EMAIL_FROM:no-reply@mail-am-nonprod.platform.hmcts.net}
