job:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  postgresql:
    enabled: true
    ROLE_ASSIGNMENT_DB_HOST: "{{ .Release.Name }}-postgresql"
    ROLE_ASSIGNMENT_DB_NAME: role_assignment
    ROLE_ASSIGNMENT_DB_PORT: 5432
    ENABLE_DB_MIGRATE: true
global:
    jobKind: CronJob