job:
  image: 'hmctspublic.azurecr.io/am/role-assignment-batch-service:latest'
  ingressHost: am-role-assignment-batch-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  applicationPort: 4099
  aadIdentityName: am
  kind: CronJob
  global:
    jobKind: CronJob
  keyVaults:
    am:
      secrets:
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: am-role-assignment-service-s2s-secret
          alias: AM_ROLE_ASSIGNMENT_SERVICE_SECRET
        - name: role-assignment-service-POSTGRES-PASS
          alias: ROLE_ASSIGNMENT_DB_PASSWORD
        - name: am-sendgrid-api-key
          alias: AM_SENDGRID_API_KEY
        - name: role-assignment-service-LD-SDK-KEY
          alias: LD_SDK_KEY
  environment:
    ROLE_ASSIGNMENT_DB_PORT: 5432
    ROLE_ASSIGNMENT_DB_NAME: role_assignment
    ROLE_ASSIGNMENT_DB_HOST: am-role-assignment-service-postgres-db-{{ .Values.global.environment }}.postgres.database.azure.com
    ROLE_ASSIGNMENT_DB_USERNAME: am@am-role-assignment-service-postgres-db-{{ .Values.global.environment }}
    LAUNCH_DARKLY_ENV: "{{ .Values.global.environment }}"
postgresql:
  enabled: false
