job:
  image: 'hmctspublic.azurecr.io/am/role-assignment-batch-service:latest'
  ingressHost: am-role-assignment-batch-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  applicationPort: 4099
  aadIdentityName: am
  kind: CronJob
  schedule: "*/10 * * * *"
  global:
    jobKind: CronJob
  keyVaults:
    am:
      secrets:
        - role-assignment-service-POSTGRES-PASS
        - AppInsightsInstrumentationKey
        - am-role-assignment-service-s2s-secret
  environment:
    ROLE_ASSIGNMENT_DB_PORT: 5432
    ROLE_ASSIGNMENT_DB_NAME: role_assignment
    ROLE_ASSIGNMENT_DB_HOST: am-role-assignment-service-postgres-db-{{ .Values.global.environment }}.postgres.database.azure.com
    ROLE_ASSIGNMENT_DB_USERNAME: am@am-role-assignment-service-postgres-db-{{ .Values.global.environment }}
postgresql:
  enabled: false
