job:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    ROLE_ASSIGNMENT_DB_HOST: "{{ .Release.Name }}-postgresql"
    ROLE_ASSIGNMENT_DB_NAME: "{{ .Values.postgresql.postgresqlDatabase}}"
    ROLE_ASSIGNMENT_DB_USERNAME: "{{ .Values.postgresql.postgresqlUsername}}"
    ROLE_ASSIGNMENT_DB_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    ROLE_ASSIGNMENT_DB_PORT: "{{ .Values.postgresql.postgresqlPort}}"
    ROLE_ASSIGNMENT_DB_OPTIONS: "?stringtype=unspecified"
    ENABLE_DB_MIGRATE: true
  keyVaults:
    am:
      secrets:
        - role-assignment-service-POSTGRES-PASS
        - AppInsightsInstrumentationKey
        - am-role-assignment-service-s2s-secret
global:
    jobKind: CronJob
postgresql:
  enabled: true
  image:
    tag: '11.3.0'
    postgresqlUsername: am
    postgresqlPassword: am
    postgresqlDatabase: role_assignment
    postgresqlPort: 5432
  persistence:
    enabled: false