java:
  image: 'hmctspublic.azurecr.io/am/role-assignment-batch-service:aat-4accd009'
  ingressHost: am-role-assignment-batch-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  applicationPort: 4098
  aadIdentityName: am
  kind: CronJob
  schedule: "*/10 * * * *"
  global:
    jobKind: CronJob
