job:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    ROLE_ASSIGNMENT_DB_HOST: "{{ .Release.Name }}-postgresql"
    ROLE_ASSIGNMENT_DB_NAME: role_assignment
    ROLE_ASSIGNMENT_DB_USERNAME: am
    ROLE_ASSIGNMENT_DB_PASSWORD: am
    ROLE_ASSIGNMENT_DB_PORT: 5432
    ROLE_ASSIGNMENT_DB_OPTIONS: "?stringtype=unspecified"
    ENABLE_DB_MIGRATE: true

      - name: user-profile-api-s2s-secret
          alias: idam.s2s-auth.totp_secret
            - name: user-profile-api-POSTGRES-PASS
              alias: spring.datasource.password
            - name: ApplicationInsightsInstrumentationKey
              alias: azure.application-insights.instrumentation-key
            - name: LD-SDK-KEY
              alias: RD_LD_SDK_KEY
  keyVaults:
    am:
      secrets:
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: am-role-assignment-service-s2s-secret
          alias: AM_ROLE_ASSIGNMENT_SERVICE_SECRET
  global:
    jobKind: CronJob

postgresql:
  enabled: true
  image:
    tag: '11.3.0'
  postgresqlUsername: am
  postgresqlPassword: am
  postgresqlDatabase: role_assignment
  postgresqlPort: 5432
  persistence:
    enabled: false
