job:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
    am:
      secrets:
        - AppInsightsInstrumentationKey
        - am-role-assignment-service-s2s-secret
        - dummy
  environment:
    ROLE_ASSIGNMENT_DB_HOST: "{{ .Release.Name }}-postgresql"
    ROLE_ASSIGNMENT_DB_NAME: role_assignment
    ROLE_ASSIGNMENT_DB_USERNAME: am
    ROLE_ASSIGNMENT_DB_PASSWORD: am
    ROLE_ASSIGNMENT_DB_PORT: 5432
    ROLE_ASSIGNMENT_DB_OPTIONS: "?stringtype=unspecified"
    ENABLE_DB_MIGRATE: true
  global:
    jobKind: CronJob

postgresql:
  enabled: true
  image:
    tag: '11.3.0'
  postgresqlUsername: am
  postgresqlPassword: am
  postgresqlDatabase: role_assignment
  postgresqlPort: 5432
  persistence:
    enabled: false
