job:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    ROLE_ASSIGNMENT_DB_HOST: "{{ .Release.Name }}-postgresql"
    ROLE_ASSIGNMENT_DB_NAME: role_assignment
    ROLE_ASSIGNMENT_DB_PORT: 5432
    ROLE_ASSIGNMENT_DB_USERNAME: am
    ENABLE_DB_MIGRATE: true
global:
    jobKind: CronJob
postgresql:
  enabled: true
  image:
    tag: '11.3.0'
  postgresqlUsername: am
  postgresqlPassword: am
  postgresqlDatabase: role_assignment
  persistence:
    enabled: false